### ISSUE TITLE
Heroku version is down (04.02.2022)

### ISSUE THREAD

**Issue by Muetzilla** [zwazel/autobattler#7]
Hi Zwazel, your Heroku version is down!
Could you fix this?

https://zwazels-autobattler.herokuapp.com/

**Comment by zwazel** [comment]
ES ISCH IM MOMENT IN FUCKING MAINTENANCE DU LAPPE JUNGE SHUUUUUT

**Comment by Muetzilla** [comment]
Aber ich will jz druff

**Comment by zwazel** [comment]
nein

**Comment by zwazel** [comment]
Guten Tag
Die Webseite sollte nun wieder erreichbar sein.

yesyes

**Comment by Muetzilla** [comment]
@zwazel sie isch wieder down...

**Comment by zwazel** [comment]
HEROKU ISCH AU NÜMM GRATIS
